packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - lucide-react@1.44.0
  - maplibre-gl@6.9.1
  - '@upstash/blob@0.0.5'
